<?php

return [
    'self_service_enabled' => env('BEACON_SELF_SERVICE_ENABLED', false),
    'minecraft_versions' => array_values(array_filter(array_map(
        'trim',
        explode(',', env('BEACON_MINECRAFT_VERSIONS', '1.21.8,1.21.4,1.20.4,1.20.1'))
    ))),
    'rate_limit' => [
        'api' => (int) env('BEACON_API_RATELIMIT', 60),
        'api_period' => (int) env('BEACON_API_RATELIMIT_PERIOD', 1),
        'content' => (int) env('BEACON_CONTENT_RATELIMIT', 20),
        'content_period' => (int) env('BEACON_CONTENT_RATELIMIT_PERIOD', 1),
        'poll' => (int) env('BEACON_POLL_RATELIMIT', 120),
        'poll_period' => (int) env('BEACON_POLL_RATELIMIT_PERIOD', 1),
    ],
    'modrinth' => [
        'base_url' => 'https://api.modrinth.com/v2',
        'allowed_download_hosts' => ['cdn.modrinth.com'],
        'user_agent' => env('BEACON_MODRINTH_USER_AGENT', 'PuShitcake/BeaconPanel'),
        'timeout' => (int) env('BEACON_MODRINTH_TIMEOUT', 10),
        'cache_ttl' => (int) env('BEACON_MODRINTH_CACHE_TTL', 300),
    ],
    'modpacks' => [
        'enabled' => env('BEACON_MODPACKS_ENABLED', false),
        'require_stopped_server' => true,
        'backup_before_mutation' => true,
        'max_archive_bytes' => (int) env('BEACON_MODPACK_MAX_ARCHIVE_BYTES', 2147483648),
        'max_extracted_bytes' => (int) env('BEACON_MODPACK_MAX_EXTRACTED_BYTES', 8589934592),
        'operation_timeout_minutes' => (int) env('BEACON_MODPACK_OPERATION_TIMEOUT', 60),
        'power_transition_timeout_seconds' => (int) env('BEACON_MODPACK_POWER_TIMEOUT', 120),
        'nest' => [
            'name' => 'Beacon',
            'author' => 'support@beacon.invalid',
            'installer_egg' => 'Beacon Modpack Installer',
        ],
        'runtime_eggs' => [
            'vanilla' => env('BEACON_EGG_VANILLA', 'Vanilla Minecraft'),
            'paper' => env('BEACON_EGG_PAPER', 'Paper'),
            'fabric' => env('BEACON_EGG_FABRIC', 'Vanilla Minecraft'),
            'forge' => env('BEACON_EGG_FORGE', 'Forge Minecraft'),
            'neoforge' => env('BEACON_EGG_NEOFORGE', 'Forge Minecraft'),
            'quilt' => env('BEACON_EGG_QUILT', 'Vanilla Minecraft'),
        ],
        'java_images' => [
            8 => 'ghcr.io/pterodactyl/yolks:java_8',
            11 => 'ghcr.io/pterodactyl/yolks:java_11',
            16 => 'ghcr.io/pterodactyl/yolks:java_16',
            17 => 'ghcr.io/pterodactyl/yolks:java_17',
            21 => 'ghcr.io/pterodactyl/yolks:java_21',
            25 => 'ghcr.io/pterodactyl/yolks:java_25',
        ],
        'providers' => [
            'modrinth' => [
                'name' => 'Modrinth',
                'base_url' => 'https://api.modrinth.com/v2',
                'download_hosts' => ['cdn.modrinth.com'],
                'image_hosts' => ['cdn.modrinth.com'],
                'enabled' => true,
            ],
            'curseforge' => [
                'name' => 'CurseForge',
                'base_url' => 'https://api.curseforge.com/v1',
                'download_hosts' => ['edge.forgecdn.net', 'mediafilez.forgecdn.net'],
                'image_hosts' => ['media.forgecdn.net', 'mediafilez.forgecdn.net'],
                'api_key' => env('BEACON_CURSEFORGE_API_KEY'),
                'enabled' => true,
            ],
            'ftb' => [
                'name' => 'Feed The Beast',
                'base_url' => 'https://api.feed-the-beast.com/v1/modpacks',
                'download_hosts' => ['api.feed-the-beast.com'],
                'image_hosts' => ['cdn.feed-the-beast.com'],
                'enabled' => true,
            ],
            'atlauncher' => [
                'name' => 'ATLauncher',
                'base_url' => 'https://api.atlauncher.com/v1',
                'download_hosts' => ['cdn.atlauncher.com', 'api.atlauncher.com'],
                'image_hosts' => [],
                'enabled' => true,
            ],
            'technic' => [
                'name' => 'Technic',
                'base_url' => 'https://api.technicpack.net',
                'download_hosts' => ['api.technicpack.net', 'solder.technicpack.net', 'servers.technicpack.net'],
                'image_hosts' => ['cdn.technicpack.net'],
                'build' => env('BEACON_TECHNIC_BUILD', 'multimc'),
                'enabled' => true,
            ],
            'voidswrath' => [
                'name' => 'Voids Wrath',
                'base_url' => 'https://www.voidswrath.com',
                'download_hosts' => ['www.voidswrath.com', 'voidswrath.com'],
                'image_hosts' => ['www.voidswrath.com', 'voidswrath.com'],
                'enabled' => env('BEACON_VOIDSWRATH_ENABLED', false),
            ],
        ],
    ],
    'content' => [
        'max_file_bytes' => (int) env('BEACON_CONTENT_MAX_FILE_BYTES', 268435456),
        'max_total_bytes' => (int) env('BEACON_CONTENT_MAX_TOTAL_BYTES', 536870912),
        'max_dependencies' => (int) env('BEACON_CONTENT_MAX_DEPENDENCIES', 50),
        'max_dependency_depth' => (int) env('BEACON_CONTENT_MAX_DEPENDENCY_DEPTH', 8),
        'require_stopped_server' => env('BEACON_CONTENT_REQUIRE_STOPPED_SERVER', true),
        'backup_before_mutation' => env('BEACON_CONTENT_BACKUP_BEFORE_MUTATION', true),
    ],
    'minecraft_configuration' => [
        'require_stopped_server' => env('BEACON_CONFIG_REQUIRE_STOPPED_SERVER', true),
        'max_file_bytes' => 262144,
    ],
];
